// Name of the task: Handle a Rejected Promise with catch

// theory: catch is the method used when your promise has been rejected. It is executed immediately after a promise's reject method is called. Hereâ€™s the syntax:

/*

myPromise.catch(error => {

});

*/

// error is the argument passed in to the reject method.

// task: Add the catch method to your promise. Use error as the parameter of its callback function and log error to the console.

// solution: